### ISSUE TITLE
Parsing golemsp status output is not a good idea

### ISSUE THREAD

**Issue by etam** [vciancio/golem-node-server#2]
It's not meant to be parsed. The `golemsp status` command itself is using `yagna` and `ya-provider` commands to get all the info. See https://github.com/golemfactory/yagna/blob/master/golem_cli/src/status.rs

For example to get node name use `ya-provider --json config get`

**Comment by etam** [comment]
Also yagna provides some metrics itself at `http://127.0.0.1:7465/metrics-api/v1/expose`

**Comment by tworec** [comment]
Here at Golem Factory, we are encouragedd by your work @vciancio !
Your creative contribution is giving us fresh hope and faith, that our stuff is not only ours. ✌️ 
Keep up the great work towards better UX for the Provider.

@etam comment is fully valid here. Pls rather use `yagna ... --json` and `ya-provider --json` or `yagna` REST endpoints to get info about provider state and health.

We will also love to hear what info is missing and what would you be interested no know more about Provider status.
Cheers!

**Comment by vciancio** [comment]
Awesome, thanks guys! @etam I tried the endpoint and it was refusing connection for some reason. Will have to try and dig further on that.

Right now I'm focused on removing the regex. I noticed the following command. Are these files? How do I access these stats?

~~~
$ ya-provider preset list-metrics

Duration       golem.usage.duration_sec
CPU              golem.usage.cpu_sec
~~~

@tworec I guess one thing that is a bit off is that `ya-provider config get` returns the subnet, but not the network itself.

~~~
$ ya-provider config get

Node name: rambolicious
Subnet: public-beta
Account: 0x320febbc9d8c61e6dceb5e49708b6df27646ffff
~~~

(w/o touching env variables at least) I was able to find it via `yagna payment status`. That seemed to be the only place it was printed out. Is there another way to find the network?

**Comment by tworec** [comment]
> @tworec I guess one thing that is a bit off is that `ya-provider config get` returns the subnet, but not the network itself.

The default network used by `ya-provider` is `mainnet`.
`ya-provider` CLI uses config files to get info about the current state. There is no other way.
And I wanted to avoid to persist `rinkeby` when one decides to use it. Thats why it is not in `ya-provider config get`


> (w/o touching env variables at least) I was able to find it via `yagna payment status`. That seemed to be the only place it was printed out. Is there another way to find the network?

The only method to distinguish which network is used by already running `ya-provider` is to check subscribed offers via REST call to yagna Market API.

If this one-liner returns ETH addr it indicates that `mainnet` is being used:
```
curl --header "Authorization: Bearer `yagna app-key list --json | jq -r .values[0][1]`" http://127.0.0.1:7465/market-api/v1/offers | jq '.[].properties."golem.com.payment.platform.zksync-mainnet-glm.address"'
```
and if this -- `rinkeby`:
```
curl --header "Authorization: Bearer `yagna app-key list --json | jq -r .values[0][1]`" http://127.0.0.1:7465/market-api/v1/offers | jq '.[].properties."golem.com.payment.platform.zksync-rinkeby-glm.address"'
```

The approach you've used within #3 via `yagna paymant status` is not valid.
